[phases.install]
cmds = [
    'composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-req=ext-mongodb',
    'npm install',
    'npm run build'
]

[phases.build]
cmds = [
    'chmod -R 775 storage bootstrap/cache'
]

[start]
cmd = 'php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT'
